language: node_js
node_js:
- "14.15.1"
dist: bionic
sudo: false
cache:
  directories:
    - node_modules
before_deploy:
  - npm install netlify-cli -g
  - yarn build
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: master
